name: 'Release Erlang Application'
inputs:
  rebar3_arg:
    description: 'arguments for rebar3'
    required: true
    default: 'tar'
    


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REBAR3_ARG: ${{ inputs.rebar3_arg }}
